# 悪い例: Stackを分けすぎ
class VpcStack(Stack): ...
class SubnetStack(Stack): ...
class SecurityGroupStack(Stack): ...
class RdsStack(Stack): ...
class LambdaStack(Stack): ...
class ApiGatewayStack(Stack): ...
class S3Stack(Stack): ...
# 7つのStackが相互に依存...
